### PR TITLE
List filtering

### LINKED ISSUE #15: Limit by namespace, filter, etc.
Ref. how the approve plugin works.

Let me know if more details are needed :)

### PR DESCRIPTION
**Pull request by knan-md**
Closes #15. Adds namespace and filter parameters to list, with same syntax as in approve plugin.

Depends on and includes #20 just for convenience. Ping me if I should redo it as standalone.

### CODE REVIEW

**Comment by solewniczak** [comment]
The "overview" parameter produces one page link per each user. I think that your intention was to show each page only once.

I understand that the meaning of overview is: "return the page if all of the ireadit users is in the state provided by state parameter". It will produce following possibilities:

- overview + read: show the page only if all the users read it
- overview + unread: show the page only if it has been never read by anyone (but are under control of ireadit plugin)
- overview + not read:  show the page only if no one read its current revision (but might have been read previously) (this is probably what you want to achieve by your commit)
- overview + outdated: should probably work as "overview + not read"

Do I understand you idea correctly?

**Comment by knan-md** [comment]
Hm, yes, I didn't really test what happened for overview in the case of a page that could be acked by multiple users. The use case is really "we create a personal page for each user, they need to read and ack it with ireadit, we want to have a list of pages that has not been acked by anyone".

**Comment by solewniczak** [comment]
Clear. We should do it as I suggested. It will be more general and will cover your use case too.

**Comment by knan-md** [comment]
I'm not quite sure how to achieve that in the current code. Especially overview+read. Could you sketch out the approach you're thinking of?

**Comment by solewniczak** [comment]
[Here](https://github.com/gkrid/dokuwiki-plugin-ireadit/tree/knan-md-filtering)  I've added "GROUP BY I.page" to overview query. It works differently than I previously suggested but still can be useful and it should work for you too:
- overview + read: show the page if anyone has read it
- overview + unread: show the page if no one has ever read it
- overview + outdated: show the page if no one has read it's last revision but was read by someone previously
- overview + not read: show the page if no one has read it's last revision

If it works for you I will merge it into mainline.

**Comment by knan-md** [comment]
Tested your branch, works fine here. Please merge.

Thanks!

**Comment by solewniczak** [comment]
Could you update the documentation?

**Comment by knan-md** [comment]
Updated. Thanks!

**Pull request merged**
